-- #487 Phase 3 : ajout du suivi de traitement sur les demandes de droits.
--
-- Lors de la validation d'une demande par un gestionnaire (applicationManager
-- ou userManager), on persiste l'identifiant du gestionnaire ayant traité la
-- demande. La date de validation est captée par la colonne `updateDate`
-- existante (mise à jour automatiquement par la upsert clause de la repo).
--
-- == Choix du type ==
--
-- Type uuid brut, sans contrainte de clé étrangère vers oresiuser :
--
--   - Le domaine EntityRef ( cf. main/V1 ) impose NOT NULL ; or treatedBy
--     est null tant que la demande n'a pas été traitée. Inutilisable.
--
--   - Une FK vers public.oresiuser entraînerait, à toute opération DDL
--     ultérieure sur cette colonne ( ALTER, DROP, etc. ), un
--     AccessExclusiveLock sur public.oresiuser. Le flux createApplication
--     tient déjà un AccessShareLock sur cette table via le check de
--     permission ( @PreAuthorize -> getCurrentUser ) ; l'attente est
--     indéfinie ( self-deadlock entre deux connexions du même flux logique ).
--
-- L'intégrité référentielle est assurée côté applicatif :
-- {@link UserRepository#findById(UUID)} renvoie null si l'utilisateur a
-- été supprimé, et le DTO {@link RightsRequestResult} expose alors un
-- {@code treatedByLogin} null. Pour ce besoin de simple traçabilité
-- d'audit, c'est suffisant.
ALTER TABLE RightsRequest
    ADD COLUMN IF NOT EXISTS treatedBy uuid;
