---
    title: Rédaction du fichier de configuration
    
    about: 
        id: config_file
        template: marquee
        links: 
          - icon: caret-left
            text: Page précédente
            href: vocabulaire.qmd
          - icon: caret-right
            text: Page suivante
            href: ../fichier_echange/data.md
            
    abstract: >
        Vous trouverez ci-dessous des exemples décrivant les parties attendues dans le fichier de configuration pour qu'il
        soit valide. 
---

# <a id="creation" />La création :

Vous trouverez ci-dessous des exemples décrivant les parties attendues dans le fichier de configuration pour qu'il
soit valide. 

**Attention le format Yaml est sensible,** il faut donc respecter l'indentation.

Il y a 6 parties (<span style="color: orange">sans indentation</span>) attendues dans le fichier :

* OA_version

::: {.callout-tip title="OA_version" collapse="true" #openadom_version}
Cela détermine la version du moteur openADOM charger de lire le fichier de configuration. En cas de version incompatible avec celle du moteur une erreur sera renvoyée.

Actuellement la version du navigateur est la version {{<var openadom.version>}}
:::

* {{<var page-refs.application.link>}},
* {{<var page-refs.data.oa>}},
* {{<var page-refs.etiquettes.oa>}},
* {{<var page-refs.additionalFiles.oa>}}
* {{<var page-refs.rightsRequest.oa>}}

<span style="color:orange">l'indentation du fichier yaml est très importante.</span>

Afin de faciliter l'écriture du fichier de configuration, nous avons mit : 
* soit "OA_" devant des noms réservés (ex : "OA_version")
* soit les noms réservés sont en MAJUSCULE (ex : "__ REFERENCE __")
