build_openadom_doc:
  image: rocker/verse:latest
  stage: pages
  script:
    - cp README.md documentations/openadom/fichiers/README.md
    - cd documentations/openadom
    - Rscript -e "install.packages('quarto')"
    - quarto render
    - mv _site public
  artifacts:
    paths:
      - public
    #rules:
    #  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

    #rules:
    #- if: ($CI_JOB_MANUAL== "true" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)