image: alpine:latest

stages:
  - build
  - pages

build_doc:
  image:
    name: registry.gitlab.com/vincenttam/pandoc-mermaid-docker
    entrypoint: [""]
  stage: build
  script:
    - mkdir public
    - pandoc documentations/DOC.md -o public/doc.pdf -V fontsize=12pt -V linestretch=1 -V linkcolor=black --number-sections  -V documentclass=scrreprt -F mermaid-filter --toc
    - pandoc documentations/Documentation_fichier_Yaml.md -o public/fichier_de_configuration.pdf -V fontsize=12pt -V linestretch=1 -V linkcolor=black --number-sections  -V documentclass=scrreprt -F mermaid-filter --toc
    - pandoc documentations/Lexique_yaml.md -o public/lexique.pdf -V fontsize=12pt -V linestretch=1 -V linkcolor=black --number-sections  -V documentclass=scrreprt -F mermaid-filter --toc
    - pandoc README.md documentations/doc_addon.md -o public/index.html -V fontsize=12pt -V linestretch=1 -V linkcolor=black --number-sections  -V documentclass=scrreprt -F mermaid-filter --toc


  artifacts:
    paths:
      - public

  only:
    variables:
      - $CI_COMMIT_BRANCH == "master"
    changes:
      - "documentations/*.md"

pages:
  stage: pages
  needs: ["build_doc"]
  script:
    - ls public

  artifacts:
    paths:
      - public

  only:
    variables:
      - $CI_COMMIT_BRANCH == "master"
    changes:
      - "documentations/*.md"