build_openadom_doc:
  image: rocker/verse:latest
  stage: build
  script:
    - set -x
    - cp README.md documentations/openadom/fichiers/readme.md
    - cp src/test/resources/data/configuration/schemaExample.yaml documentations/openadom/fichiers/schema_example.yaml
    - cat documentations/openadom/fichiers/schema_example.yaml >> documentations/openadom/fichiers/schema-example.qmd
    - echo "\`\`\`" >> documentations/openadom/fichiers/schema-example.qmd
    - cd documentations/openadom
    - ls
    - Rscript -e "install.packages('quarto')"
    - quarto render
    - pwd
    - cd ../..
    - ls
    - mkdir -p public
    - mv documentations/openadom/_site/* public/
  artifacts:
    paths:
      - public

pages:
  stage: pages
  needs: ["build_openadom_doc"]
  script:
    - ls public
  artifacts:
    paths:
      - public
