build_openadom_doc:
  image: rocker/rstudio:latest #rocker/r-rmd
  stage: build
  script:
    - set -x
    - Rscript -e "install.packages(c('rmarkdown', 'knitr'), repos='https://cloud.r-project.org')"
    - cp README.md documentations/openadom/fichiers/readme.md
    - cp src/test/resources/data/configuration/schemaExample.yaml documentations/openadom/fichiers/schema_example.yaml
    - cd documentations/openadom
    - ls
    - quarto render
    - pwd
    - cd ../..
    - ls
    - mkdir -p public
    - mv documentations/openadom/_site/* public/
  artifacts:
    paths:
      - public

pages:
  stage: pages
  needs: ["build_openadom_doc"]
  script:
    - ls public
  artifacts:
    paths:
      - public
