# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: docker:19.03.12
services:
- docker:dind
cache:
  paths:
  - "./.m2/repository"
  key: "$CI_BUILD_REF_NAME"
variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=./.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''
stages:
- build
- test
- package
maven_build:
  image: maven:3.6.3-openjdk-11
  stage: build
  script: mvn --batch-mode clean compile
  tags:
  - docker
maven_test_rest_1:
  image: maven:3.6.3-openjdk-11
  stage: test
  script: mvn --batch-mode clean test -Ptest_rest_1
  tags:
  - docker
maven_test_rest_1_ACBB:
  image: maven:3.6.3-openjdk-11
  stage: test
  script: mvn --batch-mode clean test -Ptest_rest_1_ACBB
  tags:
  - docker
maven_test_rest_1_Haute_Frequence:
  image: maven:3.6.3-openjdk-11
  stage: test
  script: mvn --batch-mode clean test -Ptest_rest_1_Haute_Frequence
  tags:
  - docker
maven_test_rest_2:
  image: maven:3.6.3-openjdk-11
  stage: test
  script: mvn --batch-mode clean test -Ptest_rest_2
  tags:
  - docker
maven_test_checker:
  image: maven:3.6.3-openjdk-11
  stage: test
  script: mvn --batch-mode clean test -Ptest_checker
  tags:
  - docker
maven_test_model:
  image: maven:3.6.3-openjdk-11
  stage: test
  script: mvn --batch-mode clean test -Ptest_model
  tags:
  - docker
maven_test_persistence:
  image: maven:3.6.3-openjdk-11
  stage: test
  script: mvn --batch-mode clean test -Ptest_persistence
  tags:
  - docker
maven:
  image: maven:3.6.3-openjdk-11
  stage: package
  script: mvn --batch-mode clean package -Dmaven.test.skip=true
  tags:
  - docker
maven_registry:
  image: maven:3.6.3-openjdk-11
  stage: package
  script:
  - MVN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
  - mvn versions:set -DnewVersion=$CI_COMMIT_BRANCH.$MVN_VERSION
  - mvn versions:commit
  - mvn deploy -Pmia -s ci-settings.xml
npm:
  image: node:12-alpine
  stage: package
  script:
  - cd ui
  - npm ci
  - npm run build
  tags:
  - docker
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
