image: docker:stable


# Pour l'utilisation de testcontainers
# https://www.testcontainers.org/supported_docker_environment/continuous_integration/gitlab_ci/
services: &dind_definition
  - name: docker:23.0.1-dind
    alias: docker
    command: [ '--tls=false' ]

cache:
  paths:
    - ./.m2/repository
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=./.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: tcp://docker:2375
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2
  # Depuis la version 18.09, l'image docker dind génère un certificat TLS, et pour le bon fonctionnement des services, ce certificat doit être partagé par l'ensemble de ces derniers !
  # Le lien ci-dessous explique la procédure à suivre au niveau des runners afin de partager le certificat généré sous forme d'un volume :
  # https://about.gitlab.com/releases/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  # comme on n'a pas accès à la configuration des runners, on désactive explicitement la génération d'un certificat TLS
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - pages
  - sonarqube-check
  - sonarqube-vulnerability-report
  - test
  - package
  # Docker image build
  - build_env
  - trigger   # trigger openadom/deployment

maven_build:
  image: maven:3.9.11-amazoncorretto-25
  stage: build
  script:
    - mvn --batch-mode clean compile test-compile -DskipTests
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .m2/repository/
  artifacts:
    paths:
      - target/
  tags:
    - docker
  rules:
    - if: $CI_JOB_MANUAL!= "true"

include:
  # - local: .gitlab_test_mvn.yml
  # - local: .gitlab_test_ui.yml
  # - local: .gitlab_package.yml
  - local: .gitlab_build_doc.yml
    path: .
  - local: .gitlab_test_mvn.yml
    path: .
  - local: .gitlab-ci_docker.yml
    path: .
  - local: .gitlab-ci_sonar.yml
    path: .
# - local: .gitlab_build_doc2.yml