# Pour l'utilisation de testcontainers
# https://www.testcontainers.org/supported_docker_environment/continuous_integration/gitlab_ci/
services:
  - docker:dind

variables:
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375"
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

stages:
  - build

maven:
  image: maven:3.6.3-openjdk-11
  stage: build
  script: mvn --batch-mode clean package
  tags:
    - docker
