npm_test:
  image: cypress/browsers:node-18.15.0-chrome-106.0.5249.61-1-ff-99.0.1-edge-114.0.1823.51-1
  stage: test
  script:
    # install dependencies
    - cd ui
    - npm ci --legacy-peer-deps
    - export NODE_OPTIONS=--openssl-legacy-provider
    # start the server in the background
    - npm run serve >/dev/null 2>file.txt &
    - npm run i18n:report
    - npm run lint
    # run Cypress tests
    - export NODE_OPTIONS=''
    - npx cypress run
  artifacts:
    when: always
    paths:
      - ui/cypress/videos/**/*.mp4
      - ui/cypress/screenshots/**/*.png
    expire_in: 1 day
  needs:
    - maven_test_rest_1
    - maven_test_rest_others
  rules:
    - if: $CI_JOB_MANUAL!= "true"