build_openadom_doc:
  image: rocker/verse:latest
  stage: build
  script:
    - set -x
    - cp README.md documentations/openadom/fichiers/readme.md
    - cp src/test/resources/data/configuration/schemaExample.yaml documentations/openadom/fichiers/schema_example.yaml
    - cd documentations/openadom
    - ls
    - Rscript -e "install.packages('quarto')"
    - quarto render
    - quarto render fichiers/about.qmd --to pdf --output about.pdf
    - quarto render fichiers/autres/database.qmd --to pdf --output autres__database.pdf
    - quarto render fichiers/autres/internationalization.qmd --to pdf --output autres__internationalization.pdf
    - quarto render fichiers/autres/lexique_yaml.qmd --to pdf --output autres__lexique_yaml.pdf
    - quarto render fichiers/autres/yaml_format.qmd --to pdf --output autres__yaml_format.pdf
    - quarto render fichiers/enReflexion/a_savoir.md --to pdf --output enreflexion__a_savoir.pdf
    - quarto render fichiers/enReflexion/reference_checker.md --to pdf --output enreflexion__reference_checker.pdf
    - quarto render fichiers/examples/configuration_min/description.qmd --to pdf --output examples__configuration_min__description.pdf
    - quarto render fichiers/fichier_echange/aide_fichier.md --to pdf --output fichier_echange__aide_fichier.pdf
    - quarto render fichiers/fichier_echange/basic_components.qmd --to pdf --output fichier_echange__basic_components.pdf
    - quarto render fichiers/fichier_echange/computed_components.md --to pdf --output fichier_echange__computed_components.pdf
    - quarto render fichiers/fichier_echange/constant_components.md --to pdf --output fichier_echange__constant_components.pdf
    - quarto render fichiers/fichier_echange/data.md --to pdf --output fichier_echange__data.pdf
    - quarto render fichiers/fichier_echange/dynamic_components.qmd --to pdf --output fichier_echange__dynamic_components.pdf
    - quarto render fichiers/fichier_echange/etiquettes.md --to pdf --output fichier_echange__etiquettes.pdf
    - quarto render fichiers/fichier_echange/pattern_components.md --to pdf --output fichier_echange__pattern_components.pdf
    - quarto render fichiers/fichier_echange/verificateurs.md --to pdf --output fichier_echange__verificateurs.pdf
    - quarto render fichiers/introduction/1.0_installation.md --to pdf --output introduction__installation.pdf
    - quarto render fichiers/introduction/1.2..Fichier\ d\'échange.md --to pdf --output introduction__fichier_dechange.pdf
    - quarto render fichiers/introduction/1_Introduction.md --to pdf --output introduction__introduction.pdf
    - quarto render fichiers/pour_aller_plus_loin/authorization.md --to pdf --output pour_aller_plus_loin__authorization.pdf
    - quarto render fichiers/pour_aller_plus_loin/component_qualifiers.md --to pdf --output pour_aller_plus_loin__component_qualifiers.pdf
    - quarto render fichiers/pour_aller_plus_loin/expressionGroovy.md --to pdf --output pour_aller_plus_loin__expressiongroovy.pdf
    - quarto render fichiers/pour_aller_plus_loin/internationnalisation_i18n.md --to pdf --output pour_aller_plus_loin__internationnalisation_i18n.pdf
    - quarto render fichiers/pour_aller_plus_loin/submission.md --to pdf --output pour_aller_plus_loin__submission.pdf
    - quarto render fichiers/README.md --to pdf --output readme.pdf
    - pwd
    - cd ../..
    - ls
    - mkdir -p public
    - mv documentations/openadom/_site/* public/
  artifacts:
    paths:
      - public

pages:
  stage: pages
  needs: ["build_openadom_doc"]
  script:
    - ls public
  artifacts:
    paths:
      - public
