version: '3'

services:
  postgresql:
    image: postgres:10.14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=xxxxxxxx
      - POSTGRES_DB=ore-si
