package fr.inra.oresing.domain.exceptions.configuration;

import lombok.Getter;

import java.util.Arrays;
import java.util.stream.Collectors;

@Getter
public enum ConfigurationException {

    authorizationScopeMissingReferenceCheckerForAuthorizationScope, //Dans le type de données {dataName}, vous définissez un <i>authorisationScope</i> {authorizationScopeName} qui fais référence au <i>component</i>  {component} de la <i>variable</i>  {variable} . Afin de pouvoir fournir une liste de valeurs sur lesquelles portera l'authorisation, vous devez définir un  <i>computationChecker</i>  de type  <i>Reference</i>   au <i>component</i> .,
    authorizationScopeComponentKeyMissingVariable, //Il faut indiquer la variable dans laquelle on recueille les informations spatiales à laquelle rattacher la donnée pour la gestion des droits jeu de données <code>{dataName}</code> pour l'autorisation <code>{authorizationScopeName}</code>. Les valeurs possibles sont : <code>{variables}</code>,
    authorizationScopeComponentKeyUnknownVariable, //<code>{variable}</code> ne fait pas partie des colonnes connues <code>{knownVariables}</code>,
    authorizationScopeComponentReftypeNull, //Aucune référence n'a été définie pour le composant <code>{component}</code> de la variable <code>{variable}</code>. Les références acceptées sont: <code>{knownPatterns}</code>,
    authorizationScopeComponentReftypeUnknown, //La référence <code>{refType}</code> du composant <code>{component}</code> de la variable <code>{variable}</code> n'a pas été déclarée. Les références acceptées sont : <code>{knownPatterns}</code>,
    authorizationScopeComponentWrongChecker, //Le composant <code>{component}</code> de la variable <code>{variable}</code> ne peut pas être utilisé comme portant l’information temporelle car ce n’est pas une donnée déclarée comme <code>{expectedChecker}</code>,
    authorizationComponentKeyMissingComponent, //Il faut indiquer le composant de la variable <code>{variable}</code> dans laquelle on recueille les informations spatiales à laquelle rattacher la donnée pour le gestion des droits jeu de données <code>{dataName}</code> pour l'autorisation <code>{authorizationName}</code>. Les valeurs possibles sont : <code>{knownComponents}</code>,
    authorizationComponentKeyunknownComponent, //<code>{component}</code> ne fait pas partie des composants connus pour la variable <code>{variable}</code>. Les composants connus sont : <code>{knownComponents}</code>,
    badAuthorizationScopeForRepository, //L'autorisation <code>{submissionScope}</code>) doit être <code>{expectedValue}/code> et non <code>{givenValue}</code>,
    characterNotAcceptInName, //Il y a des caractère non accepté dans le nom de l'application : <code>{name}</code>,
    checkerExpressionReturnedFalse, //La contrainte suivante n'est pas respectée : <code>{expression}</code>,
    csvBoundToUnknownVariable, //Dans le format CSV, l’en-tête <code>{header}</code> est lié à la variable <code>{variable}</code> qui n’est pas connue. Les variables connues sont : <code>{variables}</code>,
    csvBoundToUnknownComponent, //Dans le format CSV, l’en-tête <code>{header}</code> est lié à la variable <code>{variable}</code> mais elle n’a pas de composant <code>{component}</code>. Les composants connus sont : <code>{components}</code>,
    duplicatedHeaders, //Les en-têtes suivants sont dupliqués : <code>{duplicatedHeaders}</code>,
    duplicatedLineInDatatype, //Dans le fichier de données {file}, la ligne {lineNumber} a le même identifiant {duplicateKey} que les lignes {duplicatedRows},
    duplicatedLineInReference, //Dans le fichier du référentiel {file}, la ligne {lineNumber} a le même identifiant {duplicateKey} que les lignes {otherLines},
    emptyHeader, //Le fichier contient un en-tête de colonne vide à la ligne {headerLine},
    exception, //Il manque la chaine de traduction pour l'erreur suivante. Merci de vérifiez que ce n'est pas un problème d'indantation avant de contacter les administrateurs.,
    headerColumnPatternNotMatching, //Erreur dans le format de l'en-tête de colonne. Format à respecter : <code>{expectedHeaderColumnPattern}</code><br/>En-tête actuel : <code>{actualHeaderColumn}</code>,
    illegalCheckerConfigurationParameterForReferenceColumnChecker, //Pour le référentiel <code>{referenceToValidate}</code> et la colonne <code>{column}</code>, un contrôle <code>{checkerName}</code> est utilisé mais il n'accepte pas de paramètre <code>{parameterName}</code>,
    illegalCheckerConfigurationParameterForValidationRuleInDataType, //Pour le type de données <code>{dataName}</code> et la règle de validation <code>{validationRuleDescriptionEntryKey}</code>, un contrôle <code>{checkerName}</code> est utilisé mais il n'accepte pas de paramètre <code>{parameterName}</code>,
    illegalCheckerConfigurationParameterForValidationRuleInReference, //Pour le référentiel <code>{referenceToValidate}</code> et la règle de validation <code>{validationRuleDescriptionEntryKey}</code>, un contrôle <code>{checkerName}</code> est utilisé mais il n'accepte pas de paramètre <code>{parameterName}</code>,
    illegalCheckerConfigurationParameterForComponentChecker, //Pour le type de données <code>{dataName}</code>, le composant <code>{component}</code> de la variable <code>{datum}</code>, un contrôle <code>{checkerName}</code> est utilisé mais il n'accepte pas de paramètre <code>{parameterName}</code>,
    illegalGroovyExpressionForValidationRuleInDataType, //Pour la règle de validation <code>{lineValidationRuleKey}</code> du type de données <code>{dataName}</code>, l’expression renseignée <code>{expression}</code> n’est pas correcte. Erreur de compilation de l’expression à la ligne <code>{compilationError.lineNumber}</code> (colonne <code>{compilationError.columnNumber}</code>) message '<code>{compilationError.message}</code>',
    illegalGroovyExpressionForValidationRuleInReference, //Pour la règle de validation <code>{lineValidationRuleKey}</code> de la référence {reference}, l’expression renseignée <code>{expression}</code> n’est pas correcte. Erreur de compilation de l’expression à la ligne <code>{compilationError.lineNumber}</code> (colonne <code>{compilationError.columnNumber}</code>) message '<code>{compilationError.message}</code>',
    invalidCapturingGroupForDatatypeRepository, //Dans la section repository du datatype <code>{dataName}</code> l'authorizationScope <code>{scopeName}</code> n'existe pas. Valeurs possibles <code>{registerScopes}</code>.,
    invalidCapturingGroupForDatatypeRepositoryAuthorizationScope, //Dans la section repository du datatype <code>{dataName}</code> l'authorizationScope <code>{scopeName}</code> est <code>{scopeToken}</code>; il doit être compris entre 0 et {countGroups}.,
    invalidCapturingGroupForEndDateDatatypeRepositoryDate, //Dans la section repository du datatype <code>{dataName}</code> le groupe de capture de la date de fin <code>{token}</code> être compris entre 0 et {countGroups}.,
    invalidCapturingGroupForStartDateDatatypeRepositoryDate, //Dans la section repository du datatype <code>{dataName}</code> le groupe de capture de la date de début <code>{token}</code> être compris entre 0 et {countGroups}.,
    invalidDate, //Pour le composant identifié : <code>{target}</code> la date <code>{value}</code> ne respecte pas le format attendu : <code>{pattern}</code>. ,
    invalidDateWithColumn, //Pour la colonne : <code>{target}</code> la date <code>{value}</code> ne respecte pas le format attendu : <code>{pattern}</code>. ,
    invalidDurationForDateCheckerForValidationRuleInDataType, //La 'duration' <code>{duration}</code> définie pour la règle de validation <code>{validationRuleDescriptionEntryKey}</code> du type de données <code>{dataName}</code> est incorrecte,
    invalidDurationForDateCheckerForValidationRuleInReference, //La 'duration' <code>{duration}</code> définie pour la règle de validation <code>{validationRuleDescriptionEntryKey}</code> du référentiel <code>{reference}</code> est incorrecte,
    invalidDurationForReferenceColumnDateChecker, //La 'duration' <code>{duration}</code> définie pour la colonne <code>{column}</code> du référentiel <code>{referenceToValidate}</code> est incorrecte,
    invalidDurationForComponentDateChecker, //La 'duration' <code>{duration}</code> définie pour le composant <code>{component}</code> de la variable <code>{variable}</code> du type de données <code>{dataName}</code> est incorrecte,
    invalidFloat, //Pour le composant identifié : <code>{target}</code> la valeur <code>{value}</code> doit être un nombre décimal.,
    invalidFloatWithColumn, //Pour la colonne : <code>{target}</code> la valeur <code>{value}</code> doit être un nombre décimal.,
    invalidFormat, //Erreur à la ligne <code>{lineNumber}</code> (colonne <code>{columnNumber}</code>) : '<code>{value}</code>' n’a pas le bon format. Le type attendu est <code>{authorizedValues}</code>,
    invalidHeaders, //En-têtes de colonne invalides. Les colonnes attendues sont : <code>{expectedColumns}</code><br/>Les colonnes actuelles sont : <code>{actualColumns}</code><br/>Il manque les colonnes : <code>{missingComponents}</code><br/>Les colonnes suivantes sont inconnues : <code>{unknownComponent}</code>,
    invalidInteger, //Pour le composant identifié : <code>{target}</code> la valeur <code>{value}</code> doit être un entier.,
    invalidIntegerWithColumn, //Pour la colonne : <code>{target}</code> la valeur <code>{value}</code> doit être un entier.,
    invalidInternationalizedColumns, //Dans la description du référentiel <code>{reference}</code>, les colonnes <code>{unknownUsedAsInternationalizedColumns}</code> sont déclarées comme faisant partie de colonnes internationalisables alors qu’elles n’existent pas. Colonnes connues : <code>{knownComponents}</code>,
    invalidInternationalizedColumnsForDataType, //Dans la surcharge du référentiel <code>{reference}</code> de la description du type de donnée <code>{dataName}</code>, les colonnes <code>{unknownUsedAsInternationalizedColumns}</code> sont déclarées comme faisant partie de colonnes internationalisables alors qu’elles n’existent pas. Colonnes connues : <code>{knownComponents}</code>,
    invalidPatternForDatatypeRepository, //Dans la section repository du datatype <code>{dataName}</code> l' expression de recherche est invalide.,
    invalidPatternForDateCheckerForValidationRuleInDataType, //Le format de date <code>{pattern}</code> défini pour la règle de validation <code>{validationRuleDescriptionEntryKey}</code> du type de données <code>{dataName}</code> est incorrect,
    invalidPatternForDateCheckerForValidationRuleInReference, //Le format de date <code>{pattern}</code> défini pour la règle de validation <code>{validationRuleDescriptionEntryKey}</code> du référentiel <code>{reference}</code> est incorrect,
    invalidPatternForReferenceColumnDateChecker, //Le format de date <code>{pattern}</code> défini pour la colonne <code>{column}</code> du référentiel <code>{referenceToValidate}</code> est incorrect,
    invalidPatternForReferenceColumnRegularExpressionChecker, //L'expression régulière <code>{pattern}</code> défini pour la colonne <code>{column}</code> du référentiel <code>{referenceToValidate}</code> est incorrect,
    invalidPatternForRegularExpressionCheckerForValidationRuleInDataType, //L'expression régulière <code>{pattern}</code> défini pour la règle de validation <code>{validationRuleDescriptionEntryKey}</code> du type de données <code>{dataName}</code> est incorrect,
    invalidPatternForRegularExpressionCheckerForValidationRuleInReference, //L'expression régulière <code>{pattern}</code> défini pour la règle de validation <code>{validationRuleDescriptionEntryKey}</code> du référentiel <code>{reference}</code> est incorrect,
    invalidPatternForComponentDateChecker, //Le format de date <code>{pattern}</code> défini pour le composant <code>{component}</code> de la variable <code>{variable}</code> du type de données <code>{dataName}</code> est incorrect,
    invalidPatternForComponentRegularExpressionChecker, //L'expression régulière <code>{pattern}</code> défini pour le composant <code>{component}</code> de la variable <code>{variable}</code> du type de données <code>{dataName}</code> est incorrect,
    invalidReference, //Pour le composant identifié : <code>{target}</code> la valeur <code>{value}</code> n'existe pas dans la référence <code>{refType}</code>. Valeurs attendues <code>{referenceValues}</code>.,
    invalidReferenceWithColumn, //Pour la colonne : <code>{target}</code>  la valeur <code>{value}</code> n'existe pas dans la référence <code>{refType}</code>. Valeurs attendues <code>{referenceValues}</code>.,
    missingAggregationComponentForChart, //Dans la description du graphe de la variable <code> {variable} </code> du type de données <code> {dataName} </code>, le componsant <code> {aggregationComponent}</code> de la variable d'aggrégation <code> {aggregationVariable}</code> n'est pas déclarée.<br /> Valeurs attendues <code>{components}</code>,
    missingAggregationVariableForChart, //Dans la description du graphe de la variable <code> {variable} </code> du type de données <code> {dataName} </code>, la variable d'aggrégation <code> {aggregationVariable}</code> n'est pas déclarée.<br /> Valeurs attendues <code>{variables}</code>,
    missingAuthorizationForDatatype, //La section submissionScope doit être présente dans la description du type de données <code>{datatype}</code>,
    missingAuthorizationScopeComponentKey, //Il faut indiquer au moins un groupe de variables (et leur composants) dans le(s)quel(s) on recueille les informations spatiales à rattacher la donnée pour le gestion des droits jeu de données <code>{dataName}</code>,
    missingBoundToForConstantDescription, //Dans la section format->constant du dataName {dataName} vous devez remplir la section boundTo.,
    missingComponentNumberOrHeaderNameForConstantDescription, //Dans la section format->constant du dataName {dataName} vous devez indiquer un numéro de ligne ou un nom d'en-tête.,
    missingComponentReferenceForCheckerInDataType, //Dans la description du type de données {dataName} et la validation <code>{validationRuleDescriptionEntryKey}</code> le vérificateur de valeur <code>{checkerName}</code> déclare des variables/composants inconnus <code>{missingComponents}</code> : valeurs possible<code>{knownComponents}</code>,
    missingComponentReferenceForCheckerInReference, //Dans la description de la référence {reference} et la validation <code>{validationRuleDescriptionEntryKey}</code> le vérificateur de valeur <code>{checkerName}</code> déclare des colonnes inconnues <code>{missingComponents}</code> : valeurs possible<code>{knownComponents}</code>,
    missingDataTypeTagDeclaration, //Dans le dataName <code>{sectionName}</code>, l'étiquette <code>{tagName}</code> n'est pas déclarée.<br/>. Elle doit appartenir à la liste des étiquettes <code>{declaredTag}</code>,
    missingExportHeaderNameForConstantDescription, //Dans la section format->constant du dataName {dataName} vous devez spécifier un exportHeaderName.,
    missingKeyColumnsForReference, //Dans la description du référentiel <code>{reference}</code>, vous devez déclarer les colonnes (au moins une) qui composent la clé naturelle,
    missingNameForCheckerForValidationRuleInDataType, //Pas de nom pour le computationChecker dans le type de données :<code>{dataName}</code>, <code>{lineValidationRuleKey}</code>.<br />On attend un nom de computationChecker. Dans une section <code>name :</code>.<br />Les types de computationChecker attendus sont : <code>[{acceptedCheckerNames}]</code>,
    missingNameForCheckerForValidationRuleInReference, //Pas de nom pour le computationChecker dans la reference :<code>{referenceToValidate}</code>, <code>{validationRuleDescriptionEntryKey}</code>.<br />On attend un nom de computationChecker. Dans une section <code>name :</code>.<br />Les types de computationChecker attendus sont : <code>[{acceptedCheckerNames}]</code>,
    missingNameForCheckerForComponent, //Pas de nom pour le computationChecker dans le type de données :<code>{datatype}</code>, pour la variable :<code>{variable}</code>, au component :<code>{component}</code>. Dans une section <code>name :</code>.<br />Les types de computationChecker attendus sont : <code>[{knownCheckerNames}]</code>,
    missingNameForCheckerInReferenceColumn, //Pas de nom pour le computationChecker dans la reference :<code>{referenceToValidate}</code>, pour la colonne :<code>{column}</code>.<br />On attend un nom de computationChecker. Dans une section <code>name :</code>.<br />Les types de computationChecker attendus sont : <code>[{knownCheckerNames}]</code>,
    missingParamColumnReferenceForCheckerInDataType, //Dans la description du type de données <code>{dataName}</code>, la règle de validation <code>{validationRuleDescriptionEntryKey}</code> ne précise pas sur quelles variables/composants la règle doit s'exécuter en déclarant un paramètre <code>components</code>,
    missingParamColumnReferenceForCheckerInReference, //Dans la description de la <code>{reference}</code>, la règle de validation <code>{validationRuleDescriptionEntryKey}</code> ne précise pas sur quelles colonnes la règle doit s'exécuter en déclarant un paramètre <code>columns</code>,
    missingParentColumnForReferenceInCompositeReference, //Dans la  référence composite <code>{compositeReference}</code> la <i>parentKeyColumn</i> <code>{parentKeyColumn}</code> n'existe pas dans la référence <code>{reference}</code>.,
    missingParentLineInRecursiveReference, //Dans le fichier du référentiel {reference} la valeur d'identifiant {missingReferencesKey} pour le  parent n'existe pas. Valeurs acceptées {knownReferences},
    missingParentRecursiveKeyColumnForReferenceInCompositeReference, //Dans la  référence composite <code>{compositeReference}</code> la <i>parentRecursiveKey</i> <code>{parentRecursiveKey}</code> n'existe pas dans la référence <code>{reference}</code>.,
    missingReferenceColumnsTagDeclaration, //Dans le référentiel <code>{sectionName}</code> de la colonne <code>{variableName}</code>, l'étiquette <code>{tagName}</code> n'est pas déclarée.<br/>. Elle doit appartenir à la liste des étiquettes <code>{declaredTag}</code>,
    missingReferenceForChecker, //Pour le type de données <code>{dataName}</code>, la donnée <code>{datum}</code>, le composant <code>{component}</code>, il faut préciser le référentiel parmi <code>{reference}</code>,
    missingReferenceForCheckerInDataType, //Pour le type de données <code>{dataName}</code>, la validation <code>{validationKey}</code>, il faut préciser le référentiel parmi <code>{reference}</code>,
    missingReferenceForCheckerInReference, //Pour la reference <code>{reference}</code>, la validation <code>{validationKey}</code>, il faut préciser le référentiel parmi <code>{reference}</code>,
    missingReferenceForCheckerInReferenceColumn, //Pour la reference <code>{referenceToValidate}</code>, il faut indiquer le référentiel à utiliser pour le contrôle de la valeur de <code>{column}</code> parmi <code>{knownReferences}</code>,
    missingReferenceInCompositereference, //Tous les composants de la  reference composite <code>{compositeReference}</code> doivent déclarer une référence,
    missingReferentielTagDeclaration, //Dans le référentiel <code>{sectionName}</code>, l'étiquette <code>{tagName}</code> n'est pas déclarée.<br/>. Elle doit appartenir à la liste des étiquettes <code>{declaredTag}</code>,
    missingRequiredExpressionForValidationRuleInDataType, //Pour la règle de validation <code>{lineValidationRuleKey}</code> du type de données <code>{dataName}</code>, vous devez renseigner l’expression à évaluer pour contrôler que la règle est respectée par les données,
    missingRequiredExpressionForValidationRuleInReference, //Pour la règle de validation <code>{lineValidationRuleKey}</code> de la référence {reference}, vous devez renseigner l’expression à évaluer pour contrôler que la règle est respectée par les données,
    missingRowLineForConstantDescription, //Dans la section format->constant du dataName {dataName} vous devez indiquer un numéro de ligne.,
    missingStandardDeviationComponentForChart, //Dans la description du graphe de la variable <code> {variable} </code> du type de données <code> {dataName} </code>, l'écart type  <code> {standardDeviation}</code> n'est pas un composant déclaré.<br />Valeurs attendues <code>{components}</code>,
    missingTagDeclaration, //Dans le referentiel {referenceName}, l'étiquette {tagName} n'est pas déclarée.<br/>. Elle doit appartenir à la liste des étiquettes {declaredTag},
    missingTimeScopeComponentKey, //Il faut indiquer la variable (et son composant) dans laquelle on recueille la période de temps à laquelle rattacher la donnée pour le gestion des droits jeu de données <code>{dataName}</code>,
    missingUnitComponentForChart, //Dans la description du graphe de la variable <code> {variable} </code> du type de données <code> {dataName} </code>, l'unité  <code> {unit}</code> n'est pas un composant déclaré.<br />Valeurs attendues <code>{components}</code>,
    missingValueComponentForChart, //Dans la description du graphe de la variable <code> {variable} </code> du type de données <code> {dataName} </code>, la valeur <code> {valueComponent}</code> n'est pas un composant déclaré.<br />Valeurs attendues <code>{components}</code>,
    missingComponentDescriptionTagDeclaration, //Dans le dataName <code>{sectionName}</code> à la section <code>data</code> de la variable <code>{variableName}</code> au compenent <code>{compenentName}</code>, l'étiquette <code>{tagName}</code> n'est pas déclarée.<br/>. Elle doit appartenir à la liste des étiquettes <code>{declaredTag}</code>,
    missingVariableDescriptionTagDeclaration, //Dans le dataName <code>{sectionName}</code> à la section <code>data</code> de la variable <code>{variableName}</code>, l'étiquette <code>{tagName}</code> n'est pas déclarée.<br/>. Elle doit appartenir à la liste des étiquettes <code>{declaredTag}</code>,
    noCapturingGroupForDatatypeRepository, //Dans la section repository du datatype <code>{dataName}</code> l' expression de recherche ne contient aucun groupe de capture.,
    norightforpublish, //Vous n'avez pas les droits sur le type de donnée <code>{dataName}</code> de l'application <code>{application}</code> de publier les valeurs de la ligne  <code>{lineNumber}</code>.,
    overlappingpublishedversion, //Il existe un autre jeu de données dont une version est publiée et dont la période est chevauchante avec la version du jeu de données que vous souhaitez publier.  Veuillez dépublier la version de cet autre jeu de données pour pouvoir publier votre fichier. <code>{overlapingFiles]</code>,
    patternNotMatched, //Pour le composant identifié : <code>{target}</code> la valeur <code>{value}</code> ne respecte pas le format attendu : <code>{pattern}</code>.,
    patternNotMatchedWithColumn, //Pour la colonne : <code>{target}</code> la valeur <code>{value}</code> ne respecte pas le format attendu : <code>{pattern}</code>.,
    requiredParentKeyColumnInCompositeReferenceForReference, //Dans la  référence composite <code>{compositeReference}</code> la référence <code>{reference}</code> fait référence à <code>{referenceTo}</code> mais ne déclare pas de <i>parentKeyColumn</i> .,
    requiredReferenceInCompositeReferenceForParentKeyColumn, //Aucune référence n'a été déclarée  pour la <i>parentKeyColumn</i> <code>{parentKeyColumn}</code> dans la référence composite <code>{compositeReference}</code> .,
    requiredValue, //Pour le composant identifié : <code>{target}</code> la valeur ne peut pas être nulle.,
    requiredValueWithComponent, //Pour la composant : <code>{target}</code> la valeur ne peut pas être nulle.,
    sameHeaderLineAndFirstRowLineForConstantDescription, //Dans la section format->constant du dataName {dataName} la ligne d'en-tête ne doit pas être egale à la ligne de données.,
    timeScopeComponentKeyMissingVariable, //Il faut indiquer la variable dans laquelle on recueille la période de temps à laquelle rattacher la donnée pour le gestion des droits jeu de données <code>{dataName}</code>. Valeurs possibles <code>{variables}</code>,
    timeScopeComponentKeyUnknownVariable, //<code>{variable}</code> ne fait pas partie des colonnes connues <code>{knownVariables}</code>,
    timeScopeComponentPatternUnknown, //Le composant <code>{component}</code> de la variable <code>{variable}</code> ne peut pas être utilisé comme portant l’information temporelle car le format de date '<code>{pattern}</code>' n’est pas géré. Formats acceptés : <code>{knownPatterns}</code>,
    timeScopeComponentWrongChecker, //Le composant <code>{component}</code> de la variable <code>{variable}</code> ne peut pas être utilisé comme portant l’information temporelle car ce n’est pas une donnée déclarée comme <code>{expectedChecker}</code>,
    timeComponentKeyMissingComponent, //Il faut indiquer le composant de la variable <code>{variable}</code> dans laquelle on recueille la période de temps à laquelle rattacher la donnée pour le gestion des droits jeu de données <code>{dataName}</code>. Valeurs possibles <code>{knownComponents}</code>,
    timeComponentKeyunknownComponent, //<code>{component}</code> ne fait pas partie des composants connus pour la variable <code>{variable}</code>. Composants connus : <code>{knownComponents}</code>,
    timeRangeOutOfInterval, //La date  <code>{value}</code> est incompatible avec l'intervale de dates du dépôt. Elle doit être comprise entre <code>{from}</code> et <code>{to}</code>.,
    tooBigRowLineForConstantDescription, //Dans la section format->constant du dataName {dataName} le numéro de ligne doit être inférieur    à celui de la ligne de données.,
    tooLittleRowLineForConstantDescription, //Dans la section format->constant du dataName {dataName} le numéro de ligne doit être positif.,
    unDeclaredValueForChart, //Pour visualiser correctement le graphe de la variable <code> {variable} </code> du type de données <code> {dataName} </code>, il est nécessaire de déclarer la valeur.<br /> La valeur doit être parmi : <code>{components}</code>,
    undeclaredDataGroupForVariable, //La variable <code>{variable}</code> du dataName <code>{dataName}</code> n’est déclarée dans aucun groupe de données, elle doit l'être.,
    unexpectedHeaderColumn, //En-tête de colonne inattendu. En-tête attendu : <code>{expectedHeaderColumn}</code> <br />En-tête actuel : <code>{actualHeaderColumn}</code>,
    unexpectedHeaderColumnsInList, //En-tête de colonne inattendu. En-tête attendu : <code>{expectedHeaderColumn}</code> <br />En-tête actuel : <code>{actualHeaderColumns}</code>,
    unexpectedTokenCount, //Le nombre de jetons(token) est inattendu. Nombre attendu : <code>{expectedTokenCount}</code><br/>L'en-tête actuel : <code>{actualHeader}</code> comprend <code>{actualTokenCount}</code> tokens,
    unknownCheckerNameForValidationRuleInDataType, //Pour la règle de validation <code>{lineValidationRuleKey}</code> du type de données <code>{dataName}</code>, '<code>{checkerName}</code>' est déclaré mais ce n’est pas un contrôle connu. Les contrôles connus sont : {acceptedCheckerNames},
    unknownCheckerNameForValidationRuleInReference, //Pour la règle de validation <code>{lineValidationRuleKey}</code> de la référence <code>{reference}</code>, '<code>{checkerName}</code>' est déclaré mais ce n’est pas un contrôle connu. Les contrôles connus sont : {acceptedCheckerNames},
    unknownCheckerNameForComponent, //Dans la description du type de données {datatype} le composant <code>{component}</code>  de la variable <code>{variable}</code> et le vérificateur de valeur <code>{checkerName}</code> sont déclarés mais l'ensemble ne correspond pas à un contrôle connu<br />Les vérificateurs connus sont: <code>{knownCheckerNames}</code>,
    unknownCheckerNameForComponentCheckerInDataType, //Dans la validation du type de données <code>{dataName}</code> et la règle de validation <code>{validationRuleDescriptionEntryKey}</code>, '<code>{name}</code>' est déclaré mais ce n’est pas un contrôle connu: les valeurs possibles sont : <code>{checkerOnTargetNames}</code>.,
    unknownCheckerNameForComponentCheckerInReference, //Dans la validation de la référence <code>{reference}</code> et la règle de validation <code>{validationRuleDescriptionEntryKey}</code>, '<code>{name}</code>' est déclaré mais ce n’est pas un contrôle connu: les valeurs possibles sont :  <code>{checkerOnTargetNames}</code>.,
    unknownCheckerNameInReferenceColumn, //Pour le référentiel <code>{referenceToValidate}</code>, le contrôle défini pour la colonne <code>{column}</code> est <code>{checkerName}</code>. Or, ce n'est pas un contrôle connu. Les contrôles connus sont : <code>{knownCheckerNames}</code>,
    unknownIllegalException, //Erreur inattendue: <code>{cause}</code>,
    unknownReferenceForChecker, //Pour le type de données <code>{dataName}</code>, la donnée <code>{datum}</code>, le composant <code>{component}</code>, la référence <code>{refType}</code> n’est dans les références acceptées qui sont: <code>{reference}</code>,
    unknownReferenceForCheckerInDataType, //Pour le type de données <code>{dataName}</code>, la validation <code>{validationKey}</code>, la référence <code>{refType}</code> n’est pas dans les références acceptées qui sont: <code>{reference}</code>,
    unknownReferenceForCheckerInReference, //Pour la référence <code>{reference}</code>, la validation <code>{validationKey}</code>, la référence <code>{refType}</code> n’est pas dans les références acceptées qui sont: <code>{reference}</code>,
    unknownReferenceForCheckerInReferenceColumn, //Pour le référentiel <code>{referenceToValidate}</code> et la colonne <code>{column}</code>, le référentiel à utiliser pour le contrôle de valeur déclaré est <code>{refType}</code> qui n'est pas connu parmi <code>{knownReferences}</code>,
    unknownReferenceInCompositeReference, //La réference composite <code>{compositeReference}</code> contient les références suivantes qui ne sont pas déclarées : <code>{unknownReferences}</code>. Les références connues sont : <code>{reference}</code>,
    unknownReferenceInDatatypeReferenceDisplay, //Le référentiel <code>{reference}</code> qui décrit le type de donnée <code>{dataName}</code>, est inconnu . Les référentiels connus sont: <code>{reference}</code>,
    unknownUsedAsComponentUniqueness, //La section <code><I>uniqueness</i></code> du type de données <code>{dataName}</code> contient l'association variable_component  <code>{unknownUsedAsComponentUniqueness}</code> qui n'existent pas. Les valeurs acceptées sont : <code>{availableComponents}</code>,
    unknownVariablesInDataGroup, //La variable <code>{unknownVariables}</code> du dataName <code>{dataName}</code> dans le groupe de données <code>{dataGroup}</code> n'est pas déclarée. Les données connues sont :  <code>{variables}</code>,
    unrecognizedProperty, //Erreur à la ligne <code>{lineNumber}</code> (colonne <code>{columnNumber}</code>): <code>{unknownPropertyName}</code>, n’est pas une propriété reconnue. Les propriétés reconnues sont:  <code>{knownProperties}</code>,
    MISSING_OA_APPLICATION, //La version de l'application dit être renseignée. Elle est actuellement en version : <code>{expectedVersion}</code>,
    DUPLICATED_REFERENCE_IN_HIERARCHIC_DEPENDENCIES,
    DUPLICATED_REFERENCE_IN_DEPENDENCIES,
    NULL_REQUIRED_SECTIONS,
    BAD_ARRAY_REQUIRED_SECTIONS,
    BAD_OBJECT_REQUIRED_SECTIONS,
    BAD_ORDER_FOR_ORDER_TAG,
    EMPTY_ARRAY,
    EXPECTED_ARRAY,
    /*
    __ORDER_1__
     */
    BAD_ORDER_TAG_PATTERN,
    variableInMultipleDataGroup, //La variable <code>{variable}</code> du dataName <code>{dataName}</code> est déclarée dans plusieurs groupes de données, elle ne doit être présente que dans un seul groupe
    RESERVED_TAG_NAME,
    UNEXPECTED_SECTION_WITH_APPROACHING_LABEL_SECTION,// La section <code>{}</code> est inattendue. Peut-être vouliez-vous dire <code>{}</code>

    EMPTY_FILE,
    INVALID_DURATION_CHECKER_DATE,
    INVALID_IDENTIFICATEURS, // Dans la section {path}, les identificateurs {invalidIdentificateurs} sont invalides. Ils doivent commencer par une minuscule et ne comporter que des lettres des chiffres et le caractère souligné.
    INVALID_NATURAL_KEY,
    MISSING_COMPONENT_FOR_NATURAL_KEY_COMPUTATION,
    INVALID_MIN_MAX_FOR_CHECKER_DATE,
    INVALID_PATTERN_FOR_CHECKER_DATE,
    MISSING_COLUMN_NAME_VALIDATION,
    MISSING_PATTERN_FOR_CHECKER_DATE,
    MISSING_CHECKER_NAME,
    MISSING_REFERENCE_AND_COMPONENT_NAME,
    MISSING_REFERENCE_NAME,
    MISSING_COMPONENT_FOR_TIMESCOPE_SUBMISSION,
    MISSING_COMPONENT_FOR_COMPONENT_NAME,
    UNKNOWN_COMPONENT_FOR_COMPONENT_NAME,
    UNKNOWN_CHECKER_NAME,
    UNKNOWN_NAME_REFERENCE_SCOPE,
    UNKNOWN_STRATEGY_SUBMISSION,
    UNKNOWN_REFERENCE_NAME,
    UNKNOWN_REFERENCE_COLUMN_TO_LOOK_FOR_HEADER,
    UNSUPORTED_I18N_KEY_LANGUAGE,
    UNSUPPORTED_NAME_APPLICATION,
    MISSING_NAME_APPLICATION,
    UNSUPPORTED_VERSION_APPLICATION,
    MISSING_VERSION_APPLICATION,
    UNSUPPORTED_OPENADOM_VERSION,
    EXISTING_OPENADOM_VERSION,
    BAD_VERSION_PATTERN,
    BAD_LOCALE_LABELS,
    MISSING_ANY_MANDATORIES_SECTIONS,
    MISSING_MANDATORIES_SECTIONS,
    BAD_ENUM_SECTION_TYPE,
    MISSING_REQUIRED_ENUM_VALUE,
    BAD_INTEGER_REQUIRED_SECTIONS,
    BAD_BOOLEAN_REQUIRED_SECTIONS,
    BAD_FLOAT_REQUIRED_SECTIONS,
    UNEXPECTED_SECTIONS,
    BAD_LOCALE_SECTION_TYPE,
    BAD_LOCALE,
    BAD_GROOVY_EXPRESSION,
    /*
    submieesion
     */
    UNEXPECTED_SUBMISSION,
    UNDEFINED_COMPONENT_FOR_REFERENCE_SCOPE_AUTHORIZATION,
    INVALID_COMPONENT_REFERENCE_FOR_SUBMISSION_SCOPE_REFERENCE,
    INVALID_COMPONENT_REFERENCE_FOR_AUTHORIZATION_SCOPE_COMPONENT_NAME,
    INVALID_COMPONENT_DATE_FOR_TIMESCOPE_COMPONENT_NAME,
    /*checkers*/

    BAD_TAGS_PATTERNS,
    BAD_DOMAIN_TAG_PATTERN,
    NOT_EXPECTED_DOMAIN_TAGS,
    /*
        a positive or null number
    */
    ILLEGAL_DOMAIN_TAG_PATTERN,
    MISSING_REQUIRED_VALUE,
    MISSING_CONSTANT_IMPORT_HEADER_COLUMN_OR_ROW_NUMBER,
    MISSING_IMPORT_HEADER_PATTERN,
    BAD_CONSTANT_IMPORT_HEADER_ROW_NUMBER,
    NEGATIVE_CONSTANT_IMPORT_HEADER_ROW_NUMBER,
    NEGATIVE_CONSTANT_IMPORT_HEADER_COLUMN_NUMBER,
    MISSING_CONSTANT_IMPORT_HEADER_ROW_NUMBER,
    MISSING_CONSTANT_IMPORT_HEADER_COLUMN_NUMBER,
    DUPLICATED_COMPONENT_NAME,
    DUPLICATED_COMPONENT_HEADER,
    DUPLICATED_COMPONENT_HEADER_IN_PATTERN_COMPONENT,
    INVALID_CONFIGURATION_FILE,
    IO_EXCEPTION,
    ADDING_AUTHORIZATION_SCOPE_ATTRIBUTES_ERROR,
    REMOVING_AUTHORIZATION_SCOPE_ATTRIBUTES_ERROR,
    MISSING_COMPONENT_FOR_DISPLAY_PATTERN,
    /*
    jackson parse exeption
     */

    DUPLICATE_KEY,
    UNEXPECTED_CHARACTER,
    INVALID_TOKEN,
    UNEXPECTED_EOF,
    MALFORMED_NUMBER,
    UNTERMINATED_STRING,
    MALFORMED_COMMENT,
    UNKNOWN;

    private final String message;

    ConfigurationException() {
        message = toMessage(name());
    }

    private static String toMessage(final String name) {
        final String message = Arrays.stream(name.split("_"))
                .map(n -> n.charAt(0) + n.substring(1).toLowerCase())
                .collect(Collectors.joining());
        return message.replaceFirst("^.", message.substring(0, 1).toLowerCase());
    }
}
