### connexion
POST http://localhost:8081/api/v1/login?login=philippe&password=pfsp
Content-Type: application/json

> {%
    client.global.set("xsrfToken", response.headers.valuesOf("X-XSRF-TOKEN"));
%}

### post chart
POST http://localhost:8081/api/v1/applications/jerome_acbb_openadom_swc/additionalFiles/__charte__
Content-Type: multipart/form-data; boundary=WebAppBoundary
X-XSRF-TOKEN: {{xsrfToken}}

--WebAppBoundary
Content-Disposition: form-data; name="params"

{
  "id":"0565b1a3-421f-4e02-a44e-2ea0020cef0d",
  "fileType":"__charte__",
  "comment": "un commentaire"
}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="data.json"
Content-Type: application/octet-stream

< ./cherte2.pdf