package fr.inra.oresing.domain.rightsrequest;
import fr.inra.oresing.domain.OreSiAuthorization;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import java.util.Map;
import java.util.UUID;
import static org.assertj.core.api.Assertions.assertThat;
@Tag("domain.model")
@DisplayName("RightsRequest domain")
class RightsRequestTest {
    @Test
    @DisplayName("EMPTY_INSTANCE retourne une instance non nulle")
    void emptyInstance_isNotNull() {
        RightsRequest r = RightsRequest.EMPTY_INSTANCE();
        assertThat(r).isNotNull();
    }
    @Test
    @DisplayName("getters/setters Lombok")
    void gettersSetters() {
        RightsRequest r = new RightsRequest();
        UUID app = UUID.randomUUID();
        UUID user = UUID.randomUUID();
        r.setApplication(app);
        r.setUser(user);
        r.setComment("comment");
        r.setRightsRequestForm(Map.of("k", "v"));
        r.setSetted(true);
        assertThat(r.getApplication()).isEqualTo(app);
        assertThat(r.getUser()).isEqualTo(user);
        assertThat(r.getComment()).isEqualTo("comment");
        assertThat(r.getRightsRequestForm()).containsEntry("k", "v");
        assertThat(r.isSetted()).isTrue();
    }
    @Test
    @DisplayName("toString ne leve pas d exception")
    void toStringNoException() {
        RightsRequest r = RightsRequest.EMPTY_INSTANCE();
        assertThat(r.toString()).isNotBlank();
    }
    @Test
    @DisplayName("OreSiEntity id est genere automatiquement")
    void entityId_isAutoGenerated() {
        RightsRequest r = RightsRequest.EMPTY_INSTANCE();
        assertThat(r.getId()).isNotNull();
    }
}
