---
title: Composantes (component) de la données
subtitle: OA_basicComponents, OA_constantComponents, OA_computedComponents, OA_pattern_components, OA_dynamicComponents
abstract: Cette section définit la notion de composante de données, la manière de déclarer ces composants et de les définir depuis le fichier d''échange, ainsi que la manière dont les composantes sont enregistrées dans la base de données.
---

On appelle composante de la données toute information enregistrée en base de données permettant de décrire une donnée.

Les composantes sont enregistrées en fonction de leur méthode d'obtention et de leur type {{< var  page-refs.checker.link>}}.

On déclarera une composante en fonction de la façon de la récupérer dans le fichier ou de la définir de façon globale.

## Données déclarées dans une colonne du fichier. {#OA_importHeader}

Si la valeur correspond à la valeur sous l'en-tête, on la déclarera dans la section {{< var  page-refs.basic-comp.oa>}}. On choisira un {{< var  page-refs.vocab.link-identificateurs>}} pour cette composante.

::: {.callout-tip collapse="false" title="Déclaration d'une composante"}

| date       |
|------------|
| 23/12/2004 |
| 24/12/2004 |
| 25/12/2004 |

``` yaml
OA_data:
    OA_basicComponents:
        date: 
```
:::


Si le nom de l'en-tête ne correspond pas à l'identificateur fourni, on pourra le préciser dans la section OA_importHeader

::: {.callout-tip collapse="false" title="Déclaration d'une composante avec un en-tête spécifique"}
{{< var page-refs.data.link-cartouche >}}

| Date de prélèvement |
|---------------------|
| 23/12/2004          |
| 24/12/2004          |
| 25/12/2004          |

``` yaml
OA_data:
    OA_basicComponents:
        date: 
            OA_importHeader: "Date de prélèvement"
```
:::

## Données déclarées dans le {{< var page-refs.data.link-cartouche >}}

En utilisant l'en-tête du fichier on peut récupérer dans valeurs qui seront constantes pour toutes les lignes. On déclarera ces composantes dans la section {{< var  page-refs.constant-comp.oa>}}

On peut aussi définir une constante avec une composante ne récupérant pas de valeur à laquelle on fournit une valeur par défaut (OA_defautValue)

## Données calculées

Pour fournir une valeur calculées on déclarera sa composante dans la section {{<var page-refs.computed-comp.oa>}}

## Données correspondant à des propriétés

Ce type de données provient généralement d'un cas décrivant des données généralement sur plusieurs niveaux (récursivité) où les niveaux admettent des propriétés différentes selon les niveau.

Par exemple des taxons ou des sites ayant des propriétés différentes selon leur niveau; 

Dans ce cas on définit un référentiel de propriétés avec une colonne donnant un nom pour la propriété.

Dans le type de données utilisant ces propriétés, les colonnes "propriétés" utilisent OA_importHeaderle nom des propriétes du référentiel propriétés, éventuellement préfixé. On crée alors une définition d'une composante  {{<var page-refs.dynamic-comp.oa>}}.

voir 

- {{<var page-refs.example.link-dynamic>}}
- {{<var page-refs.example.link-taxons>}}


## Component obligatoire {#OA_mandatory}

La notion de component obligatoire est à placer au niveau de la définition du composant (pas besoin de déclarer un vérificateur)

``` yaml
    sit_nom_du_site:
        OA_mandatory: true # default false sauf si le component (colonne) est déclaré dans OA_naturalKey. 
      #Dans ce cas elle passe a true par default.
```

## Valeur obligatoire {#OA_required}

La notion de valeur obligatoire est à placer au niveau de la définition du composant (pas besoin de déclarer un vérificateur)

``` yaml
    sit_nom_du_site:
        OA_required: true # default false sauf si le component (colonne) est déclaré dans OA_naturalKey. 
      #Dans ce cas elle passe a true par default.
```



## Internationalisation

Vous pouvez modifier l'affichage de l'en-tête d'une composante en sortie en utilisant une section **OA_exportHeader**


``` yaml
OA_data:
    OA_basicComponents:
        date: 
            OA_importHeader: "Date de prélèvement"
            OA_exportHeader: 
                OA_title:
                    fr: Date de prélèvement
                    en: Date of collection
                OA_description:
                    fr: Date à laquelle le prélèvement à été effectué
                    en: Date on which the sample was taken
```